FMG-9: add 'Permission' button on the form page
formio/angular pull request #681
Opened 2020-12-10 08:17 UTC by DmitryNistratov

2020-12-14 17:20 UTC, travist requested changes

2020-12-14 17:20 UTC, travist commented on projects/angular-formio/grid/src/form/FormGridBody.component.html
> +            <button *ngIf="actionAllowed('formEdit')" class="btn btn-outline-secondary btn-sm form-btn" (click)="onRowAction($event, form, 'permissions')"><span class="fa fa-edit"></span> Permissions
This page does not exist in this repo. Won't this cause errors?

2020-12-15 16:13 UTC, yavorovsky requested changes
Should add an action like formAccess for the manager service.

2021-06-01 16:07 UTC, travist commented
Please rebase with master.

2021-12-27 15:25 UTC, closed without merging